disabled_rules:


file_length:
  warning: 500


trailing_comma:
  mandatory_comma: true


opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - explicit_self
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - modifier_order
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - untyped_error_in_catch
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_whitespace_between_cases
  - yoda_condition
  - unused_declaration: warning
  - unused_optional_binding: warning
  - force_unwrapping: error
  - redundant_type_annotation: error


private_over_fileprivate:
  validate_extensions: true
  severity: error

identifier_name:
  allowed_symbols: "_"
  min_length: 3
  max_length:
    warning: 30
    error: 40
  excluded:
    - i
    - id
    - x
    - y
    - r
    - g
    - b
    - a
    - u
    - v
    - w
    - h
    - p
    - xX
    - yY
    - x0
    - y0
    - xx
    - yy
    - dx
    - dy

line_length:
  warning: 100
  error: 120
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

