included:
  - ./Sources/MandArt

excluded:
  - Carthage
  - Pods
  - ./Sources/MandArt/ContentView.swift
  - ./Sources/MandArt/MandArtApp.swift
  - ./Sources/MandArt/MandArtDocument.swift
  - ./Sources/MandArt/MandMath.swift
  - ./Sources/MandArt/PictureDefinition.swift


opt_in_rules:
  - unused_optional_binding
  - force_try
  - line_length

disabled_rules:
  - cyclomatic_complexity
  - type_name
  - identifier_name
  - large_tuple


