name: Generate Docs

on:
  push:
    branches:
      - main
    paths:
      - Documentation.docc/**/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move Documenation.docc to code folder
        run: |
          mv Documentation.docc Sources/Mandart/

      - name: Rename Package.swift 
        run: mv Package.txt Package.swift

      - name: Generate new documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target MandArt --output-path ./docs \
            --disable-indexing \
            --transform-for-static-hosting  \
            --emit-digest \
            --target MandArt \
            --hosting-base-path 'MandArt-Docs'

      - name: Clone docs repo
        uses: actions/checkout@v2
        with:
          repository: denisecase/MandArt-Docs
          ref: main
          path: ../MandArt-Docs

      - name: Delete prior MandArt-Docs/docs folder
        run: rm -r ../MandArt-Docs/docs

      - name: Copy docs folder from MandArt to MandArt-Docs
        run: cp -R docs ../MandArt-Docs/docs

      - name: Delete new docs folder from MandArt
        run: rm -r docs

      - name: Return Documenation.docc
        run: |
          mv Sources/Mandart/Documentation.docc Documentation.docc
      
      - name: Return Package.swift to Package.txt
        run: mv Package.swift Package.txt


      